name: C Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt update && sudo apt install -y build-essential

      - name: Build project
        run: make

      - name: Run the compiler
        run: ./compiler < test_input.txt || true  # or adjust to your app’s usage
